name: Build data

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn download-datasets
      - run: yarn prepare-data
      - run: sudo apt-get install -y libuv1 libopengl0 libjpeg-turbo8 libcurl4 libicu66
      - name: Compute static maps
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn compute-maps
