name: Build data

on:
  schedule:
    - cron:  '5 7 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn download-datasets
      - run: yarn prepare-data
      - name: Prepare rendering toolchain
        run: sudo apt-get install -y libuv1 libopengl0 libjpeg-turbo8 libcurl4 libicu66
      - name: Compute static maps
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn compute-maps
      - name: Create and upload bundle
        run: yarn upload-bundle
        env:
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
          S3_VHOST: ${{ secrets.S3_VHOST }}

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          region: 'osc-fr1'
          api_token: ${{ secrets.SCALINGO_API_TOKEN }}
          app_name: 'preservonsleau-api-prod'
      - run: scalingo restart
